import { buildCacheName, resolvePrecacheList } from "./cache";
import type { ServiceWorkerOptions } from "./types";

function toJsStringArray(values: readonly string[]): string {
	return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

/**
 * ShrimpHarbor — generates the source text of a service worker file
 * implementing a cache-first strategy with an offline fallback page.
 *
 * Write the returned string to public/sw.js in the generated app.
 * This function only produces text; it does not touch the filesystem
 * or any browser-only APIs, so it is safe to call at build time.
 */
export function generateServiceWorkerSource(
	options: ServiceWorkerOptions,
): string {
	const cacheName = buildCacheName(options.cacheName, options.cacheVersion);
	const precacheList = resolvePrecacheList(options);
	const offlineFallbackUrl = options.offlineFallbackUrl;

	return `// Generated by Rakta.js ShrimpHarbor - do not edit manually.
// Re-run "bun rakta pwa:generate" to regenerate this file.

const CACHE_NAME = ${JSON.stringify(cacheName)};
const OFFLINE_FALLBACK_URL = ${JSON.stringify(offlineFallbackUrl)};
const PRECACHE_URLS = ${toJsStringArray(precacheList)};

self.addEventListener("install", (installEvent) => {
  installEvent.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (activateEvent) => {
  activateEvent.waitUntil(
    caches.keys().then((cacheKeys) =>
      Promise.all(
        cacheKeys
          .filter((cacheKey) => cacheKey !== CACHE_NAME)
          .map((staleCacheKey) => caches.delete(staleCacheKey)),
      ),
    ),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (fetchEvent) => {
  if (fetchEvent.request.method !== "GET") {
    return;
  }

  fetchEvent.respondWith(
    caches.match(fetchEvent.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }

      return fetch(fetchEvent.request)
        .then((networkResponse) => {
          const responseClone = networkResponse.clone();
          caches
            .open(CACHE_NAME)
            .then((cache) => cache.put(fetchEvent.request, responseClone));
          return networkResponse;
        })
        .catch(() => {
          if (fetchEvent.request.mode === "navigate") {
            return caches.match(OFFLINE_FALLBACK_URL);
          }

          return caches.match(fetchEvent.request);
        });
    }),
  );
});
`;
}
