import type { ProjectConfig, ProjectFile } from "../types";
import type { BackendAdapter, BackendCapabilities } from "./backendAdapter";

export const laravelCapabilities: BackendCapabilities = {
	framework: "laravel",
	language: "PHP",
	runtime: "PHP 8.2+",
	defaultDatabase: "mysql",
	supportedDatabases: ["mysql", "postgresql", "sqlite", "sawitdb"],
	authentication: "Laravel Sanctum / Session",
	middleware: "Laravel HTTP Middleware",
	validation: "Form Request / Validator",
	apiType: "REST / Blade",
	developmentCommand: "php artisan serve --port=4000",
	productionCommand: "php artisan serve --env=production",
	databaseDriver: "Eloquent ORM / SawitDB-PHP Facade",
	sawitDatabaseSupport: true,
	generationStatus: "IMPLEMENTED",
};

export const laravelAdapter: BackendAdapter = {
	identifier: "laravel",
	name: "Laravel",
	language: "PHP",
	runtime: "PHP",
	capabilities: laravelCapabilities,
	generateFiles(projectConfiguration: ProjectConfig): ProjectFile[] {
		const projectName = projectConfiguration.projectName;
		const isSawitDatabase = projectConfiguration.database === "sawitdb";

		const composerContent = JSON.stringify(
			{
				name: `rakta/${projectName}-backend`,
				type: "project",
				description: "Laravel backend generated by Rakta.js",
				require: {
					php: "^8.2",
					"laravel/framework": "^11.0",
					"laravel/sanctum": "^4.0",
					...(isSawitDatabase ? { "wowoengine/sawitdb-php": "^1.0" } : {}),
				},
				autoload: {
					"psr-4": {
						"App\\\\": "app/",
					},
				},
			},
			null,
			2,
		);

		const environmentContent = `APP_NAME=${projectName}
APP_ENV=local
APP_KEY=base64:RaktaLaravelGeneratedSecretKey2026=
APP_DEBUG=true
APP_URL=http://localhost:4000

DB_CONNECTION=${isSawitDatabase ? "sawitdb" : projectConfiguration.database}
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=${projectName}_db
DB_USERNAME=root
DB_PASSWORD=
${isSawitDatabase ? "SAWIT_DB_FILE=./storage/database.sawit\n" : ""}
`;

		const artisanContent = `#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

echo "Rakta.js Laravel CLI (Artisan Engine)\n";
echo "Run 'php artisan serve --port=4000' to start backend development server.\n";
`;

		const apiRoutesContent = `<?php

use Illuminate\\Http\\Request;
use Illuminate\\Support\\Facades\\Route;
use App\\Http\\Controllers\\AuthController;
use App\\Http\\Controllers\\UserController;

Route::get('/health', function () {
    return response()->json([
        'status' => 'ok',
        'framework' => 'Laravel',
        'timestamp' => now()->toIso8601String()
    ]);
});

Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/login', [AuthController::class, 'login']);

Route::get('/users', [UserController::class, 'index']);
`;

		const databaseConfigContent = `<?php

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
        ],
        'sawitdb' => [
            'driver' => 'sawitdb',
            'database_file' => env('SAWIT_DB_FILE', storage_path('database.sawit')),
        ],
    ],
];
`;

		const authControllerContent = `<?php

namespace App\\Http\\Controllers;

use Illuminate\\Http\\Request;
use App\\Models\\User;

class AuthController extends Controller
{
    public function register(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8',
        ]);

        $user = User::create([
            'name' => $validatedData['name'],
            'email' => $validatedData['email'],
            'password' => bcrypt($validatedData['password']),
        ]);

        return response()->json(['user' => $user, 'status' => 'success'], 201);
    }

    public function login(Request $request)
    {
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required',
        ]);

        return response()->json([
            'user' => ['id' => 1, 'email' => $credentials['email'], 'name' => 'Rhein Sullivan'],
            'token' => 'laravel_sanctum_mock_token',
        ]);
    }
}
`;

		const userControllerContent = `<?php

namespace App\\Http\\Controllers;

use Illuminate\\Http\\Request;

class UserController extends Controller
{
    public function index()
    {
        return response()->json([
            ['id' => 1, 'name' => 'Rhein Sullivan', 'role' => 'admin'],
            ['id' => 2, 'name' => 'Laravel Developer', 'role' => 'developer'],
        ]);
    }
}
`;

		const userModelContent = `<?php

namespace App\\Models;

use Illuminate\\Foundation\\Auth\\User as Authenticatable;

class User extends Authenticatable
{
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];
}
`;

		const migrationContent = `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
`;

		return [
			{ path: "backend/composer.json", content: composerContent },
			{ path: "backend/artisan", content: artisanContent },
			{ path: "backend/.env.example", content: environmentContent },
			{ path: "backend/.env", content: environmentContent },
			{ path: "backend/routes/api.php", content: apiRoutesContent },
			{ path: "backend/config/database.php", content: databaseConfigContent },
			{
				path: "backend/app/Http/Controllers/AuthController.php",
				content: authControllerContent,
			},
			{
				path: "backend/app/Http/Controllers/UserController.php",
				content: userControllerContent,
			},
			{ path: "backend/app/Models/User.php", content: userModelContent },
			{
				path: "backend/database/migrations/2026_01_01_000000_create_users_table.php",
				content: migrationContent,
			},
			{
				path: "backend/README.md",
				content: `# ${projectName} Backend (Laravel)\n\nLaravel backend generated for Rakta.js fullstack ecosystem.\n\n## Commands\n- Dev: \`php artisan serve --port=4000\`\n`,
			},
		];
	},
};
