// CLI: bun rakta rpc:types
// Regenerates shared/types/rpc.ts which re-exports AppRouter for frontend use.
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export async function rpcTypesCommand(
	cwd: string = process.cwd(),
): Promise<void> {
	const sharedTypesDir = join(cwd, "..", "shared", "types");

	if (!existsSync(sharedTypesDir)) {
		mkdirSync(sharedTypesDir, { recursive: true });
	}

	const outputPath = join(sharedTypesDir, "rpc.ts");
	const content = `// shared/types/rpc.ts
// Auto-generated by: bun rakta rpc:types
// Re-exports AppRouter type from the backend for type-safe frontend RPC calls.
// Re-run this command after modifying backend/src/rpc/router.ts.

export type { AppRouter } from "../../backend/src/rpc/router.js";
`;

	writeFileSync(outputPath, content, "utf-8");
	console.log(`\n  Generated: shared/types/rpc.ts\n`);
	console.log(`  Import in frontend:`);
	console.log(`    import type { AppRouter } from "../../shared/types/rpc";\n`);
}
