// CLI: bun rakta seo:generate
// Generates sitemap.xml and robots.txt route handlers.
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadConfig } from "../config/load-config";

export async function seoGenerateCommand(cwd: string = process.cwd()): Promise<void> {
  const config = await loadConfig(cwd);
  const appDir = join(cwd, config.appDir);

  const sitemapDir = join(appDir, "api", "sitemap.xml");
  const robotsDir = join(appDir, "api", "robots.txt");

  if (!existsSync(sitemapDir)) {
    mkdirSync(sitemapDir, { recursive: true });
    writeFileSync(
      join(sitemapDir, "route.ts"),
      `// app/api/sitemap.xml/route.ts — generated by: bun rakta seo:generate
        import { createSitemapHandler } from "rakta/seo";

        export const GET = createSitemapHandler({
        baseUrl: process.env["BASE_URL"] ?? "${config.seo.siteUrl ?? "http://localhost:3000"}",
        entries: [
            { loc: "/", changefreq: "daily", priority: 1.0 },
            { loc: "/about", changefreq: "monthly", priority: 0.8 },
        ],
        });
        `,
      "utf-8"
    );
    console.log("  Created: app/api/sitemap.xml/route.ts");
  } else {
    console.warn("  Already exists: app/api/sitemap.xml/route.ts");
  }

  if (!existsSync(robotsDir)) {
    mkdirSync(robotsDir, { recursive: true });
    writeFileSync(
      join(robotsDir, "route.ts"),
      `// app/api/robots.txt/route.ts — generated by: bun rakta seo:generate
        import { createRobotsHandler } from "rakta/seo";

        export const GET = createRobotsHandler({
        rules: [
            {
            userAgent: "*",
            allow: "/",
            disallow: ["/api/"],
            },
        ],
        sitemap: "${config.seo.siteUrl ?? "http://localhost:3000"}/api/sitemap.xml",
        });
        `,
      "utf-8"
    );
    console.log("  Created: app/api/robots.txt/route.ts");
  } else {
    console.warn("  Already exists: app/api/robots.txt/route.ts");
  }

  console.log("\n  SEO route handlers generated.\n");
}