/**
 * SSR build pipeline for Rakta.js.
 *
 * Responsibility:
 *   Generate a self-contained production server entry point that:
 *   1. Starts an HTTP server (Bun or Node compatible).
 *   2. Handles static asset serving from the client output directory.
 *   3. Handles API routes by loading compiled route modules.
 *   4. Handles page requests by serving the HTML shell with correct mode
 *      headers (full ReactDOMServer integration is in v1.3 roadmap).
 *
 * The generated server entry is designed to be portable:
 *   - Works with `bun run dist/server/index.js`
 *   - Works with `node dist/server/index.js` (with --input-type=module if ESM)
 *   - Can be wrapped by platform adapters (Vercel, Netlify, etc.)
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { SeoConfig } from "../config/defineConfig";
import { RAKTA_NAME, RAKTA_VERSION } from "../frameworkIdentity";
import type { RenderConfig } from "../render/types";

export interface SsrBuildOptions {
	readonly projectRoot: string;
	readonly outDir: string;
	/** Directory that will contain client-side assets (JS, CSS, chunks). */
	readonly clientOutDir: string;
	readonly appDir: string;
	readonly publicDir: string;
	readonly appName: string;
	readonly seo: SeoConfig;
	readonly renderConfig: RenderConfig;
	readonly port: number;
	readonly runtime: "bun" | "node";
}

export interface SsrBuildResult {
	readonly success: boolean;
	readonly serverEntry: string;
	readonly buildMs: number;
	readonly errors: string[];
}

/**
 * Generates the production server entry source code.
 * The generated file imports the Rakta runtime server and starts serving.
 */
function buildServerEntrySource(options: SsrBuildOptions): string {
	const renderConfigJson = JSON.stringify(options.renderConfig, null, 2);
	const seoJson = JSON.stringify(options.seo, null, 2);

	return `/**
 * Rakta.js Production Server
 * Generated by ${RAKTA_NAME} v${RAKTA_VERSION}
 *
 * Start: bun run dist/server/index.js
 *        node dist/server/index.js
 */

import { existsSync, readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const __SERVER_DIR__ = new URL(".", import.meta.url).pathname.replace(/\\/$/, "");
const __PROJECT_ROOT__ = resolve(__SERVER_DIR__, "..", "..");
const __OUT_DIR__ = resolve(__SERVER_DIR__, "..");
const __CLIENT_DIR__ = join(__OUT_DIR__, "client");
const __PUBLIC_DIR__ = join(__PROJECT_ROOT__, ${JSON.stringify(options.publicDir.replace(options.projectRoot, "").replace(/^[\\/]/, ""))});
const __APP_DIR__ = join(__PROJECT_ROOT__, ${JSON.stringify(options.appDir.replace(options.projectRoot, "").replace(/^[\\/]/, ""))});

const RENDER_CONFIG = ${renderConfigJson};
const SEO_CONFIG = ${seoJson};
const APP_NAME = ${JSON.stringify(options.appName)};
const PORT = Number(process.env.PORT ?? ${options.port});
const HOST = process.env.HOST ?? "0.0.0.0";

const MIME_TYPES = {
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

function mimeFor(path) {
  const ext = path.slice(path.lastIndexOf(".")).toLowerCase();
  return MIME_TYPES[ext] ?? "application/octet-stream";
}

function safeJoin(base, rel) {
  try {
    const decoded = decodeURIComponent(rel);
    const resolved = resolve(join(resolve(base), decoded));
    if (resolved === resolve(base) || resolved.startsWith(resolve(base) + "/") || resolved.startsWith(resolve(base) + "\\\\")) {
      return resolved;
    }
  } catch {}
  return null;
}

function isFile(p) {
  try { return existsSync(p) && statSync(p).isFile(); } catch { return false; }
}

function readBuildManifest() {
  try {
    const p = join(__OUT_DIR__, "build-manifest.json");
    if (isFile(p)) return JSON.parse(readFileSync(p, "utf-8"));
  } catch {}
  return null;
}

const buildManifest = readBuildManifest();
const scriptPath = buildManifest?.client?.entry
  ? buildManifest.client.entry.replace(__CLIENT_DIR__, "").replace(/\\\\/g, "/")
  : "/app.js";
const cssPath = buildManifest?.client?.css?.[0]
  ? buildManifest.client.css[0].replace(__CLIENT_DIR__, "").replace(/\\\\/g, "/")
  : "/app.css";

const CRITICAL_CSS = [
  "#rakta-root{min-height:100vh}",
  "#rakta-loading{position:fixed;inset:0;display:flex;align-items:center;",
  "justify-content:center;background:var(--rakta-bg,#0a0a0a);",
  "color:var(--rakta-fg,#fff);font-family:system-ui,sans-serif;",
  "font-size:14px;letter-spacing:.05em;z-index:9999;",
  "transition:opacity .2s ease}",
  "#rakta-loading.done{opacity:0;pointer-events:none}",
].join("");

function buildHtmlShell(title, description, scriptPath, cssPath) {
  const descMeta = description ? \`<meta name="description" content="\${description}" />\` : "";
  return \`<!DOCTYPE html>
<html lang="en" data-framework="raktajs">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="dark light" />
    <meta name="generator" content="${RAKTA_NAME}" />
    <title>\${title}</title>
    \${descMeta}
    <link rel="icon" href="/favicon.ico?v=rakta" sizes="any" />
    <link rel="preload" href="\${cssPath}" as="style" />
    <link rel="modulepreload" href="\${scriptPath}" />
    <link rel="stylesheet" href="\${cssPath}" />
    <style>\${CRITICAL_CSS}</style>
  </head>
  <body>
    <div id="rakta-root" data-rakta="true"></div>
    <div id="rakta-loading" aria-live="polite" aria-label="Loading"><span>Loading\\u2026</span></div>
    <script>
      document.addEventListener("rakta:mounted", function() {
        var el = document.getElementById("rakta-loading");
        if (el) { el.classList.add("done"); setTimeout(function(){ el.remove(); }, 300); }
      }, { once: true });
    </script>
    <script type="module" src="\${scriptPath}"></script>
  </body>
</html>\`;
}

const server = Bun.serve({
  port: PORT,
  hostname: HOST,
  async fetch(request) {
    const url = new URL(request.url);
    const { pathname } = url;

    // Static assets
    const rel = pathname.replace(/^\\/+/, "") || "index.html";
    for (const dir of [__CLIENT_DIR__, __PUBLIC_DIR__, __OUT_DIR__]) {
      const fp = safeJoin(dir, rel);
      if (fp && isFile(fp)) {
        const immutable = rel.includes("chunks/") || /\\.[a-f0-9]{8,}\\.(js|css)$/.test(rel);
        return new Response(readFileSync(fp), {
          headers: {
            "Content-Type": mimeFor(fp),
            "Cache-Control": immutable ? "public, max-age=31536000, immutable" : "public, max-age=0, must-revalidate",
            "X-Powered-By": ${JSON.stringify(RAKTA_NAME)},
          },
        });
      }
    }

    // Framework fingerprint
    if (pathname === "/.well-known/rakta" || pathname === "/.well-known/rakta.json") {
      return new Response(JSON.stringify({ framework: ${JSON.stringify(RAKTA_NAME)}, version: ${JSON.stringify(RAKTA_VERSION)} }), {
        headers: { "Content-Type": "application/json" },
      });
    }

    // Page response
    const title = SEO_CONFIG?.defaultTitle ?? APP_NAME;
    const description = SEO_CONFIG?.defaultDescription;
    const html = buildHtmlShell(title, description, scriptPath.startsWith("/") ? scriptPath : "/" + scriptPath, cssPath.startsWith("/") ? cssPath : "/" + cssPath);

    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "X-Powered-By": ${JSON.stringify(RAKTA_NAME)},
      },
    });
  },
});

const displayHost = HOST === "0.0.0.0" || HOST === "::" ? "localhost" : HOST;
console.log("\\n  ⩛ " + ${JSON.stringify(RAKTA_NAME)} + " v" + ${JSON.stringify(RAKTA_VERSION)} + " — Production Server");
console.log("    Local: http://" + displayHost + ":" + server.port + "\\n");
`;
}

/**
 * Builds the SSR server entry artifact.
 * Writes a self-contained server.js to <outDir>/server/index.js.
 */
export async function buildServerEntry(
	options: SsrBuildOptions,
): Promise<SsrBuildResult> {
	const startMs = Date.now();
	const errors: string[] = [];

	const serverDir = join(options.outDir, "server");
	mkdirSync(serverDir, { recursive: true });

	const serverEntry = join(serverDir, "index.js");

	try {
		const source = buildServerEntrySource(options);
		writeFileSync(serverEntry, source, "utf-8");
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		errors.push(`Failed to write server entry at ${serverEntry}: ${message}`);
		return {
			success: false,
			serverEntry,
			buildMs: Date.now() - startMs,
			errors,
		};
	}

	return {
		success: true,
		serverEntry,
		buildMs: Date.now() - startMs,
		errors: [],
	};
}
