import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { scanForExports } from "./scanner";
import type {
	AutoImportGeneratorOptions,
	AutoImportManifest,
	DiscoveredExport,
} from "./types";

const GENERATED_HEADER = `// This file is auto-generated by: bun rakta imports:generate
// Do not edit manually. Re-generate whenever you add or remove files.
// Note: Rakta Auto Import v0.1.0 produces a typed re-export layer.
// Import from this file in your app code:
//   import { useCounterStore, http } from "./.rakta/auto-imports";
`;

function buildImportLines(exports: ReadonlyArray<DiscoveredExport>): string {
	if (exports.length === 0) {
		return "// No exports discovered. Check your autoImport.directories config.\n";
	}

	return exports
		.map(
			(discoveredExport) => `export * from "${discoveredExport.importPath}";`,
		)
		.join("\n");
}

function buildGlobalDeclarations(
	exports: ReadonlyArray<DiscoveredExport>,
): string {
	if (exports.length === 0) return "";

	const globalLines: string[] = [];

	for (const item of exports) {
		const names = new Set<string>();
		if (item.name) names.add(item.name);
		if (item.simpleName) names.add(item.simpleName);

		for (const name of names) {
			globalLines.push(
				`  const ${name}: typeof import("${item.importPath}").default;`,
			);
		}
	}

	return `\ndeclare global {\n${globalLines.join("\n")}\n}\n`;
}

export function generateAutoImports(
	options: AutoImportGeneratorOptions,
): AutoImportManifest {
	const exports = scanForExports({
		frontendRoot: options.frontendRoot,
		directories: options.directories,
		outputDirectory: options.outputDirectory,
		...(options.extensions
			? {
					extensions: options.extensions,
				}
			: {}),
	});

	const outputDir = join(options.frontendRoot, options.outputDirectory);

	mkdirSync(outputDir, {
		recursive: true,
	});

	const tsContent = `${GENERATED_HEADER}\n${buildImportLines(exports)}\n`;

	writeFileSync(join(outputDir, "auto-imports.ts"), tsContent, "utf-8");

	if (options.generateDts) {
		const dtsContent = `// Type declarations - auto-generated by: bun rakta imports:generate\n${buildImportLines(exports)}\n${buildGlobalDeclarations(exports)}`;

		writeFileSync(join(outputDir, "auto-imports.d.ts"), dtsContent, "utf-8");
	}

	return {
		generatedAt: new Date().toISOString(),
		sourceDirectories: options.directories,
		exports,
	};
}

export function printAutoImportSummary(manifest: AutoImportManifest): void {
	console.log("\n  Rakta Auto Import");
	console.log(`  ${"─".repeat(50)}`);
	console.log(`Generated: ${manifest.generatedAt}`);
	console.log(`Exports:   ${manifest.exports.length}`);

	if (manifest.exports.length > 0) {
		console.log("");

		for (const discoveredExport of manifest.exports) {
			console.log(
				`[${discoveredExport.kind.padEnd(10)}] ${discoveredExport.name}  <-  ${discoveredExport.filePath}`,
			);
		}
	}

	console.log(`  ${"─".repeat(50)}\n`);
}
