import {
	createRaktaDetectionHeaders,
	createRaktaRuntimeFingerprint,
	RAKTA_FRAMEWORK_ID,
	RAKTA_NAME,
	RAKTA_VERSION,
	RAKTA_WEBSITE,
} from "../frameworkIdentity";
import type {
	RenderContext,
	RenderFailure,
	RenderMode,
	RenderResult,
	RenderSuccess,
} from "./types";

export interface RendererOptions {
	readonly appName: string;
	readonly title?: string | undefined;
	readonly description?: string | undefined;
	readonly faviconPath?: string | undefined;
	readonly scriptPath: string;
	readonly cssPath: string;
	readonly lang: string;
}

// HTML Shell
// Key performance choices:
//
// 1. <link rel="preload"> for CSS - tells the browser to fetch the stylesheet
//    in parallel with HTML parsing instead of waiting for the <link> tag.
//
// 2. <link rel="modulepreload"> for the JS bundle - the most impactful change.
//    Without this, the browser only discovers the script when it reaches the
//    <script type="module"> tag, then must download + parse it before any
//    React component renders. modulepreload eliminates that delay entirely:
//    the browser prefetches, parses, and compiles the module during HTML parse.
//
// 3. <meta name="color-scheme"> - prevents a flash of unstyled light background
//    on dark-mode sites while the CSS is loading.
//
// 4. Inline critical CSS for #rakta-root - prevents the blank white flash that
//    users perceive as the page "not loading", even though the network response
//    already arrived.
//
// These four changes together directly address the "response is in the network
// tab but UI doesn't appear for ~10 seconds" issue reported by users.
// The blank-screen delay was caused by late JS discovery + no loading indicator.

export function buildHtmlShell(options: RendererOptions): string {
	const title = options.title ?? options.appName;
	const faviconPath = options.faviconPath ?? "/favicon.ico";
	const faviconHref = faviconPath.includes("?")
		? faviconPath
		: `${faviconPath}?v=rakta`;
	const descriptionMeta =
		options.description !== undefined
			? `<meta name="description" content="${options.description}" />`
			: "";

	// Inline critical CSS: keeps the loading state visible immediately while
	// the full stylesheet and JS bundle are still being fetched.
	const criticalCss = `
    #rakta-root{min-height:100vh}
    #rakta-loading{
      position:fixed;inset:0;display:flex;align-items:center;
      justify-content:center;background:var(--rakta-bg,#0a0a0a);
      color:var(--rakta-fg,#fff);font-family:system-ui,sans-serif;
      font-size:14px;letter-spacing:.05em;z-index:9999;
      transition:opacity .2s ease
    }
    #rakta-loading.done{opacity:0;pointer-events:none}
  `.replace(/\n\s+/g, "");

	const runtimeFingerprint = JSON.stringify(createRaktaRuntimeFingerprint());

	return `<!DOCTYPE html>
<!-- Generated by ${RAKTA_NAME} v${RAKTA_VERSION} - ${RAKTA_WEBSITE} -->
<html lang="${options.lang}" data-framework="${RAKTA_FRAMEWORK_ID}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="dark light" />
    <meta name="generator" content="${RAKTA_NAME}" />
    <title>${title}</title>
    ${descriptionMeta}
    <link rel="icon" href="${faviconHref}" sizes="any" type="image/x-icon" />
    <link rel="shortcut icon" href="${faviconHref}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="${faviconHref}" />
    <link rel="preload" href="${options.cssPath}" as="style" />
    <link rel="modulepreload" href="${options.scriptPath}" />
    <link rel="stylesheet" href="${options.cssPath}" />
    <style>${criticalCss}</style>
  </head>
  <body>
    <div id="rakta-root" data-rakta="true"></div>
    <div id="rakta-loading" aria-live="polite" aria-label="Loading">
      <span>Loading\u2026</span>
    </div>
    <script>
      // Stable public Rakta.js framework identity.
      window.__RAKTA__ = Object.assign({}, window.__RAKTA__, ${runtimeFingerprint});
    </script>
    <script type="module">
      function hideSplash() {
        const loadingElement = document.getElementById("rakta-loading");
        if (loadingElement) loadingElement.classList.add("done");
      }
      document.addEventListener("rakta:mounted", hideSplash, { once: true });
      window.addEventListener("DOMContentLoaded", function () {
        requestAnimationFrame(function () { requestAnimationFrame(hideSplash); });
      }, { once: true });
    </script>
    <script type="module" src="${options.scriptPath}"></script>
  </body>
</html>`;
}

// Result helpers

function makeSuccess(
	html: string,
	mode: RenderMode,
	renderMs: number,
	httpStatus: number = 200,
	fromCache: boolean = false,
): RenderSuccess {
	return {
		kind: "success",
		html,
		mode,
		httpStatus,
		responseHeaders: {
			"Content-Type": "text/html; charset=utf-8",
			// Hint to CDN/proxy: do not cache HTML pages (they contain the app shell).
			// Static assets (JS/CSS) are separately cache-controlled by the server.
			"Cache-Control": "no-cache, no-store, must-revalidate",
			"X-Rakta-Mode": mode,
			"X-Rakta-Ms": String(renderMs),
			...createRaktaDetectionHeaders("bun"),
		},
		fromCache,
		renderMs,
	};
}

function makeFailure(
	reason: string,
	mode: RenderMode,
	httpStatus: number = 500,
): RenderFailure {
	return { kind: "failure", reason, mode, httpStatus };
}

// Render

/**
 * Render a page using the resolved mode from the context.
 *
 * CSR / SPA / hybrid - returns the HTML shell. React renders in browser.
 * SSR / streaming_ssr / edge / isr - returns the HTML shell. The production
 *   tide adapter performs server-side rendering by loading compiled route
 *   modules and calling ReactDOMServer.renderToString at request time.
 * SSG / CSG - the HTML shell is served in dev mode; forge/ssg.ts drives
 *   static generation at build time, writing per-route HTML files.
 */
export async function render(
	context: RenderContext,
	options: RendererOptions,
): Promise<RenderResult> {
	const startMs = Date.now();

	switch (context.mode) {
		case "csr":
		case "spa":
		case "hybrid":
			return makeSuccess(
				buildHtmlShell(options),
				context.mode,
				Date.now() - startMs,
			);

		case "ssr":
		case "streaming_ssr":
		case "edge":
		case "isr":
		case "ssg":
		case "csg":
			return makeSuccess(
				buildHtmlShell(options),
				context.mode,
				Date.now() - startMs,
			);
	}
}

export function renderNotFound(options: RendererOptions): RenderSuccess {
	return makeSuccess(buildHtmlShell(options), "csr", 0, 404);
}

export function renderServerError(
	reason: string,
	mode: RenderMode,
): RenderFailure {
	return makeFailure(reason, mode, 500);
}
