# frozen_string_literal: true

# Rakta.js Component Generator Tool
# Scaffolds production-grade React TSX components, styles, stories, and unit tests.

module Rakta
  module Generators
    class ComponentGenerator
      attr_reader :name, :category, :with_tests, :with_styles

      def initialize(name:, category: "ui", with_tests: true, with_styles: true)
        @name = sanitize_name(name)
        @category = category
        @with_tests = with_tests
        @with_styles = with_styles
      end

      # Generates TSX component code using Rakta.js conventions (Auto Import, GSAP, Tailwind)
      def generate_component_code
        <<~TSX
          // biome-ignore-all lint: Component generated by Rakta.js CLI
          // #{@name} component - Rakta.js zero-import architecture

          export interface #{@name}Props {
            readonly title?: string;
            readonly variant?: "primary" | "secondary" | "danger" | "ghost";
            readonly isFluid?: boolean;
            readonly onClick?: () => void;
            readonly children?: ReactNode;
            readonly className?: string;
          }

          export default function #{@name}({
            title = "#{@name}",
            variant = "primary",
            isFluid = false,
            onClick,
            children,
            className = "",
          }: #{@name}Props) {
            const containerRef = useRef<HTMLDivElement>(null);

            useEffect(() => {
              if (!containerRef.current) return;
              gsap.fromTo(
                containerRef.current,
                { opacity: 0, y: 12 },
                { opacity: 1, y: 0, duration: 0.3, ease: "power2.out" }
              );
            }, []);

            const variantClasses = {
              primary: "border-brand-pink bg-rose-950/30 text-white hover:bg-brand-pink/20",
              secondary: "border-surface-stroke bg-zinc-900 text-gray-200 hover:border-gray-600",
              danger: "border-red-600 bg-red-950/30 text-red-200 hover:bg-red-900/40",
              ghost: "border-transparent bg-transparent text-gray-400 hover:text-white",
            }[variant];

            return (
              <div
                ref={containerRef}
                onClick={onClick}
                className={`border px-4 py-3 font-sans transition-all duration-150 ${variantClasses} ${isFluid ? "w-full" : "w-auto"} ${className}`}
              >
                <div className="flex items-center justify-between gap-3">
                  <span className="font-mono text-xs font-bold uppercase tracking-wider">
                    {title}
                  </span>
                  <FaCircleCheck className="h-4 w-4 text-brand-pink" />
                </div>
                {children && <div className="mt-2 text-sm text-gray-300">{children}</div>}
              </div>
            );
          }
        TSX
      end

      # Generates corresponding unit test file in Bun / Jest format
      def generate_test_code
        <<~TS
          import { describe, test, expect } from "bun:test";
          import #{@name} from "./#{@name}";

          describe("#{@name} Component", () => {
            test("exports functional React component", () => {
              expect(typeof #{@name}).toBe("function");
            });

            test("matches default props structure", () => {
              const element = #{@name}({ title: "Test Title" });
              expect(element).toBeDefined();
            });
          });
        TS
      end

      private

      def sanitize_name(input)
        input.to_s.gsub(/[^a-zA-Z0-9]/, "").capitalize
      end
    end
  end
end
