# frozen_string_literal: true

# Rakta.js Route Generator Tool
# Automates creation of nested layouts, parallel slots, dynamic segment routes, and server handlers.

module Rakta
  module Generators
    class RouteGenerator
      attr_reader :route_path, :route_type

      def initialize(route_path:, route_type: :page)
        @route_path = normalize_path(route_path)
        @route_type = route_type.to_sym
      end

      # Generates a standard route page TSX file
      def generate_page_code
        page_title = @route_path.split("/").last&.capitalize || "Home"

        <<~TSX
          // biome-ignore-all lint: Route generated by Rakta.js CLI
          // #{@route_path} page - Rakta.js fullstack route

          export default function #{page_title}Page() {
            const [isLoading, setIsLoading] = useState(false);

            return (
              <main className="min-h-screen bg-black text-white p-8">
                <div className="max-w-4xl mx-auto space-y-6">
                  <header className="border-b border-surface-stroke pb-4">
                    <h1 className="text-2xl font-bold font-mono tracking-tight text-brand-pink">
                      #{page_title}
                    </h1>
                    <p className="text-sm text-gray-400 font-mono">
                      Route: #{@route_path}
                    </p>
                  </header>

                  <section className="bg-zinc-950 border border-surface-stroke p-6 rounded-none">
                    <p className="text-sm text-gray-300">
                      Rakta.js production route ready for fullstack components.
                    </p>
                  </section>
                </div>
              </main>
            );
          }
        TSX
      end

      # Generates route layout wrapper
      def generate_layout_code
        <<~TSX
          // biome-ignore-all lint: Layout generated by Rakta.js CLI
          export default function Layout({ children }: { children: ReactNode }) {
            return (
              <div className="layout-shell w-full min-h-screen flex flex-col">
                {children}
              </div>
            );
          }
        TSX
      end

      private

      def normalize_path(path)
        p = path.to_s.strip
        p.start_with?("/") ? p : "/#{p}"
      end
    end
  end
end
