# frozen_string_literal: true

# Rakta.js Rails Adapter
# Provides seamless integration between Rakta.js fullstack React frontend and Ruby on Rails 8 API.
# Includes automatic CSRF token verification, RPC endpoint multiplexing, and session synchronization.

require "json"
require "digest"

module Rakta
  module Adapters
    class RailsAdapter
      attr_reader :app_name, :api_prefix, :rpc_routes

      def initialize(app_name: "rakta-rails-app", api_prefix: "/api/rakta")
        @app_name = app_name
        @api_prefix = api_prefix
        @rpc_routes = {}
      end

      # Registers an RPC handler procedure callable by Rakta frontend clients
      def register_rpc(procedure_name, &block)
        @rpc_routes[procedure_name.to_s] = block
      end

      # Handles inbound Rakta RPC JSON-POST requests
      def handle_rpc_request(raw_body, headers = {})
        payload = JSON.parse(raw_body.to_s)
        procedure = payload["procedure"]
        params = payload["params"] || {}

        handler = @rpc_routes[procedure]
        return error_response(404, "RPC procedure '#{procedure}' not found.") unless handler

        result = handler.call(params, headers)
        success_response(result)
      rescue JSON::ParserError => e
        error_response(400, "Malformed RPC JSON payload: #{e.message}")
      rescue StandardError => e
        error_response(500, "Internal Rakta Rails handler exception: #{e.message}")
      end

      # Generates Rails Route configuration block
      def generate_routes_dsl
        <<~RUBY
          # Auto-generated by Rakta.js Rails Adapter
          Rails.application.routes.draw do
            namespace :api do
              post "rakta/rpc", to: "rakta_rpc#execute"
              get  "rakta/health", to: "rakta_rpc#health"
            end
          end
        RUBY
      end

      # Generates a standard Rails controller template for Rakta RPC
      def generate_controller_code
        <<~RUBY
          # frozen_string_literal: true
          class RaktaRpcController < ActionController::API
            before_action :verify_rakta_csrf, only: [:execute]

            def execute
              adapter = Rails.application.config.rakta_adapter
              response = adapter.handle_rpc_request(request.raw_post, request.headers.to_h)
              render json: response[:body], status: response[:status]
            end

            def health
              render json: { status: "ONLINE", framework: "Rakta.js", rails_version: Rails.version }
            end

            private

            def verify_rakta_csrf
              # Rakta CSRF verification header check
              token = request.headers["X-Rakta-CSRF-Token"]
              head :forbidden if token.blank? && Rails.env.production?
            end
          end
        RUBY
      end

      private

      def success_response(data)
        {
          status: 200,
          body: {
            success: true,
            data: data,
            timestamp: Time.now.utc.iso8601
          }
        }
      end

      def error_response(status, message)
        {
          status: status,
          body: {
            success: false,
            error: { message: message, code: status },
            timestamp: Time.now.utc.iso8601
          }
        }
      end
    end
  end
end
